name: ascii_type
version: 0.0.2
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: 'Classification and conversion of ASCII characters. Includes functions:
  isalnum, isalpha, isblank, iscntrl, isdigit, isgraph, islower, isprint, ispunct,
  isspace, isupper, isxdigit, tolower, toupper.'
homepage: https://github.com/mezoni/ascii_type.git
dependencies:
  unittest: any
dev_dependencies:
  ascii: any
